
# Global å…¨å±€é…ç½®
site_analytics: <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?df581157cd9d6219e402d25e06e06345";var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(hm, s);})();</script>
hoster: <a href="https://www.aliyun.com" target="_blank">Aliyun</a>
site_logo: /images/favicon.ico
snow: true
enable_dark: false
cdn: false

# Index é¦–é¡µé…ç½®
index:
  post_type: false

# Top Menu é¡¶éƒ¨å¯¼èˆªæ é…ç½® ï¼ˆå…·ä½“æ ¼å¼è¯·å‚ç…§æ–‡æ¡£ï¼‰
menu:
  index: /
  docs:
    submenu: true
    archives: /archives/
    search: /search/
  works: /categories/æå®¢ä¸–ç•Œ/
  notes: /categories/å­¦ä¹ å°æŠ„/
  reading: /categories/é˜…è¯»æœ‰æ„Ÿ/
  life: /categories/ç”Ÿæ´»æ—¥å¸¸/
  friends: /friends/
  lab:
    submenu: true
    ciyana-button: https://ciyana.moe/
  sites:
    submenu: true
    introduce: /about/
    github: https://github.com/FrozenLemonTee/
    twitter: https://twitter.com/frozenlemontee
    leetcode: https://leetcode-cn.com/u/frozenlemontee/
    bilibili: https://space.bilibili.com/88488273/
    project: https://github.com/FrozenLemonTee/FrozenLemonTee.github.io

label:
  index: <i class="fa fa-home"></i>é¦–é¡µ
  docs:
    submenu: <i class="fa fa-folder"></i>æ¡£æ¡ˆé¦†
    archives: <i class="fa fa-file"></i>å½’æ¡£
    search: <i class="fa fa-search"></i>æœç´¢
  works: <i class="fa fa-code"></i>æå®¢ä¸–ç•Œ
  notes: <i class="fa fa-pencil"></i>å­¦ä¹ å°æŠ„
  reading: <i class="fa fa-bookmark"></i>é˜…è¯»æœ‰æ„Ÿ
  life: <i class="fa fa-coffee"></i>ç”Ÿæ´»æ—¥å¸¸
  friends: <i class="fa fa-paw"></i>å°ä¼™ä¼´ä»¬
  lab:
    submenu: <i class="fa fa-flask"></i>å®éªŒå®¤
    ciyana-button: æ¢¦é­‡æŒ‰é’®
  sites:
    submenu: <i class="fa fa-paper-plane"></i>å…³äºæˆ‘
    introduce: è‡ªæˆ‘ä»‹ç»
    github: Githubä¸»é¡µ
    twitter: æ¨ç‰¹ä¸»é¡µ
    leetcode: åŠ›æ‰£ä¸»é¡µ
    bilibili: Bç«™ä¸»é¡µ
    project: æœ¬é¡¹ç›®é“¾æ¥

# Footer é¡µè„šé…ç½®
group_link:
contact:
  weibo:
  github: FrozenLemonTee
  mail: frozenlemontee@outlook.com
  telegram:
  twitter: frozenlemontee
  facebook:
  linkedin:
  fediverse:
    instance:
    username:
  rss:
timenotice: æœ¬ç«™å·²è¿è¡Œ
icp: æ¡‚ICPå¤‡2021001483å·
psr:

# Post Page æ–‡ç« é¡µé…ç½®
posts:
  show_cc: true
  donate: false
  share: true
  comments: waline

# Disqus [Disqus](https://disqus.com) è¯„è®ºç›¸å…³
disqus:
  shortname:

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) è¯„è®ºç›¸å…³
disqusjs:
  shortname:
  sitename:
  api:
  apikey:
  admin:
  adminlabel:

# Valine [Valine](https://valine.js.org) è¯„è®ºç›¸å…³
valine:
  app_id:
  app_key:
  visitor:
  enableQQ:

# Twikoo [Twikoo](https://twikoo.js.org) è¯„è®ºç›¸å…³
twikoo:
  env_id:

# Waline [Waline](https://waline.js.org) è¯„è®ºç›¸å…³
## ä¸ä»…é™äºä»¥ä¸‹å†…å®¹ï¼Œæ‚¨å¯ä»¥å‚ç…§ Walineçš„ [å‰ç«¯é…ç½®æ–‡æ¡£](https://waline.js.org/client/basic.html) è®¾ç½®æ‚¨éœ€è¦çš„é…ç½®é¡¹
## el å’Œ path ä¼šåœ¨é¡µé¢è‡ªåŠ¨ç”Ÿæˆï¼Œä¸å¿…åŠ å…¥
waline:
  serverURL: "https://commentsblog.vercel.app" #åç«¯æœåŠ¡å™¨åœ°å€ï¼Œå¿…å¡«
  placeholder: "è¯´ç‚¹ä»€ä¹ˆå§~(PS:ç‚¹å·¦ä¸Šè§’ç™»å½•/æ³¨å†Œå“¦)"
  avatar: "mp"
  requiredFields: ['nick','mail']
  visitor: true
  langMode:
    nick: æ˜µç§°ï¼ˆå¿…å¡«ï¼‰
    mail: é‚®ç®±ï¼ˆå¿…å¡«ï¼‰
    link: ç½‘å€

# APlayer å·¦ä¸‹è§’éŸ³ä¹æ’­æ”¾å™¨
aplayer:
  enabled: true
  playlist:
  meting:
    server: netease
    type: playlist
    id: 6613490674
  order: random

# Widgets ä¾§è¾¹æ å°æŒ‚ä»¶
sidebar: right
widgets:
- about
- toc
- category
- tagcloud
- posts
avatarUri: https://i.loli.net/2021/10/26/rIDnecjG2QAZVvf.jpg

# Fancybox æ–‡ç« å†…å›¾ç‰‡å•å‡»æ”¾å¤§
fancybox: true

# Search æœç´¢
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript ç›¸å…³é…ç½®
## ç”±äºJavascriptè¢«å‹ç¼©åéš¾ä»¥æœ‰æ•ˆç¼–è¾‘ä¸ç”Ÿæˆï¼Œå› è€Œä¸ºäº†ç®€åŒ–æ“ä½œï¼Œå°†ç›¸å…³çš„é…ç½®é¡¹åœ¨ç”Ÿæˆæ–‡ä»¶æ—¶ä»¥ç‹¬ç«‹çš„jsonæ–‡ä»¶å†™å‡ºï¼Œè°ƒç”¨æ—¶ä½¿ç”¨fetch APIè·å–ã€‚
jsconfig:
  main:
    picCDN: false
    createTime: "2021/02/12 23:00:00"
    donateBtn: "æ”¯æŒæˆ‘~"
    scanNotice: "æ‰«ä¸€æ‰«ï¼Œå¥½ä¸å¥½ï¼Ÿ"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: true
    leaveTitle: "{{{(>_<)}}}å“¦å“Ÿï¼Œå´©æºƒå•¦~"
    returnTitle: "(*Â´âˆ‡ï½€*)æ¬¸ï¼Œåˆå¥½å•¦~"
    copyrightNotice: "è¯¥å†…å®¹é‡‡ç”¨ CC BY-NC-SA 4.0 è®¸å¯åè®®ï¼Œè‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚å•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚"
    expire_day: 365

# Site verify ç«™ç‚¹éªŒè¯ç›¸å…³é…ç½®å†…å®¹
site_verify:
  google: 4qF_KlKNRhqPAo581_Hsj2bId5zyTdPTQimBBliWHGA
  baidu:
  bing: A750048D4902C65242608ECD2FDCED3F

# Friends å‹é“¾ç›¸å…³å†…å®¹
friends:
  # href: /friends/
  page:
    title: "å°ä¼™ä¼´ä»¬"
    comments: true
    description: "å°ä¼™ä¼´ä»¬åœ¨å“ªé‡Œå‘€~"
    updated: "2021-02-12"
  list:
  # - name:
  #   bio:
  #   avatar:
  #   link:
  - name: ç³–è“Â·éƒ¨è½
    bio: ğ•¹ğ–Šğ–›ğ–Šğ–— ğ–‰ğ–—ğ–”ğ–œğ–“ ğ–™ğ–ğ–Š ğ–‹ğ–†ğ–‘ğ–’ğ–Š ğ–”ğ–‹ ğ–ğ–”ğ–•ğ–Š
    avatar: https://cn.gravatar.com/avatar/a7f9e15fef26e0a540edc977e21cb3eb?s=128
    link: https://candinya.com
  - name: Davinciçš„çº¢èŒ¶é¦†
    bio: You are all stardust.
    avatar: https://cdn.jsdelivr.net/gh/DavinciEvans/Imgs-bed@master/gallery/avatar.jpg
    link: https://davincievans.top/
  - name: æŸ æª¬æµ£ç†Šé…±
    bio: LemonHXçš„å®¶
    avatar: https://pbs.twimg.com/profile_images/1570488990418993154/yPyDb_1Q_400x400.jpg
    link: https://lililikeuuu.lemonhx.moe/
  - name: æ˜Œç»´
    bio: æ˜Œç»´çš„ç½‘ç«™
    avatar: https://github.com/cw1997.png
    link: https://blog.changwei.me/
  - name: ç…é¥¼æœå­
    bio: ä¸šç²¾äºå‹¤ï¼Œè’äºå¬‰ï¼›è¡Œæˆäºæ€ï¼Œæ¯äºéš
    avatar: https://cdn2.sublimerui.top/2021/07/09/40713906.jpg
    link: https://blog.moej.cn/
  - name: æ©™å­æœ¨çš„å°æœ¨å±‹
    bio: Network, Electron, AmateurRadio
    avatar: https://blog.ypa.moe/media/image/avatar.png
    link: https://blog.ypa.moe/
  - name: æŸ æª¬å‘³çš„å¸ƒä¸ç›’å­
    bio: å¯’è‰é»æ˜ä¹‹æ—¶,ä¾¿æ˜¯é‡ç”Ÿä¹‹æ—¥ã€‚
    avatar: https://cravatar.cn/avatar/22b242a28bb848f2629f2a636bba9c03?s=400
    link: https://www.imagic.run/
  - name: Uniori
    bio: Hope for world peace.
    avatar: https://cdn.jsdelivr.net/gh/bronya5th/some-others/Gravatars/Avatar-television2.png
    link: https://blog.uniori.xyz/
  - name: MegaMUä¸ªäººç«™
    bio: è½æ—¥é»„æ²™ï¼Œç™½å¸†ç§‹æ°´ï¼Œä½ å¯çŸ¥è°çš„è®°å¿†åœ¨æ—¶ç©ºé‡Œé£ï¼Ÿ
    avatar: https://megamu.icu/images/avatar.jpg
    link: https://megamu.icu/
